// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8GXFQRUHZQ5DyB5ADTOX3aBGLPzxWBCo',
    appId: '1:431646922547:web:ab4c02139b9028fd35d046',
    messagingSenderId: '431646922547',
    projectId: 'telecare-push-notification',
    authDomain: 'telecare-push-notification.firebaseapp.com',
    databaseURL: 'https://telecare-push-notification-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telecare-push-notification.appspot.com',
    measurementId: 'G-1NKQKN5VMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl2kzEhirNN6azKMs10q8tl_RRB_pDy_w',
    appId: '1:431646922547:android:904fcf521a95763135d046',
    messagingSenderId: '431646922547',
    projectId: 'telecare-push-notification',
    databaseURL: 'https://telecare-push-notification-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telecare-push-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IklRCEd4pYcYtkWHp806ynu_DwIxhNo',
    appId: '1:431646922547:ios:218dd216ea9f951135d046',
    messagingSenderId: '431646922547',
    projectId: 'telecare-push-notification',
    databaseURL: 'https://telecare-push-notification-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telecare-push-notification.appspot.com',
    iosClientId: '431646922547-c3d0uqfmd8bet2fgjm0pl2u71mblsls3.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTelecarePkm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IklRCEd4pYcYtkWHp806ynu_DwIxhNo',
    appId: '1:431646922547:ios:218dd216ea9f951135d046',
    messagingSenderId: '431646922547',
    projectId: 'telecare-push-notification',
    databaseURL: 'https://telecare-push-notification-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telecare-push-notification.appspot.com',
    iosClientId: '431646922547-c3d0uqfmd8bet2fgjm0pl2u71mblsls3.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTelecarePkm',
  );
}
